### ISSUE TITLE
cite source for Ballot.rho

### ISSUE THREAD

**Issue by dckc** [rchain-community/community#2]
Large parts of Ballot.rho look awfully familiar. I think I wrote them. I strongly prefer preserving git history so git blame works, but at least add something in the "initial commit" message and/or the code itself. I guess I could, but it would be a lot easier if you cited the source from which you copied it, @jimscarver 

In case, I sound like a broken record, get used to it. :)

**Comment by jimscarver** [comment]
added attribution for Ballot.rho and locker.rho
